version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotels-frontend
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - default
