version: "3.8"
services:
  opensearch-node:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch-node
    environment:
      - cluster.name=opensearch-hotel-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      - OPENSEARCH_HOSTS=["https://opensearch-node:9200"]
    networks:
      - opensearch-net

  hotels-searcher:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotels-searcher
    ports:
      - 8082:8080
    environment:
      - OPENSEARCH_HOST=opensearch-node
      - OPENSEARCH_PORT=9200
    networks:
      - opensearch-net

volumes:
  opensearch-data:

networks:
  opensearch-net:
