apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: micro-app
spec:
  selector:
    app: opensearch
  ports:
  - name: rest
    port: 9200
    targetPort: 9200
  - name: inter-node
    port: 9300
    targetPort: 9300
  type: ClusterIP
