management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

microservice:
  hotels-orders:
    url: ${HOTELS_ORDERS_URL:http://localhost:8081}
  hotels-searcher:
    url: ${HOTELS_SEARCHER_URL:http://localhost:8082}
