apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels-searcher
  namespace: micro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotels-searcher
  template:
    metadata:
      labels:
        app: hotels-searcher
    spec:
      containers:
      - name: hotels-searcher
        image: cr.yandex/common/hotels-searcher:latest
        ports:
        - containerPort: 8080
        env:
        - name: OPENSEARCH_HOST
          value: "opensearch"
        - name: OPENSEARCH_PORT
          value: "9200"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
