apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels-orders
  namespace: micro-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotels-orders
  template:
    metadata:
      labels:
        app: hotels-orders
    spec:
      containers:
      - name: hotels-orders
        image: cr.yandex/common/hotels-orders:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/hotel_booking"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-user
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: postgres-password
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
