management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health

opensearch:
  host: ${OPENSEARCH_HOST}
  port: ${OPENSEARCH_PORT}
